#!/usr/bin/env bash
# Check that each public header compiles on its own.
#
# A header that only compiles because some other header happened to be included
# first is a trap for consumers: it works in this repository and breaks in
# theirs. Compiling each one in isolation catches that before it ships.
#
# Usage: scripts/check_headers.sh include/cpp_library_template/foo.hpp ...
#
# Two of the public headers (export.hpp, version.hpp) are generated by CMake, so
# a configured build tree is required. If there is none, the check reports why
# and passes rather than failing a commit for an unrelated reason.

set -euo pipefail

if [[ $# -eq 0 ]]; then
    exit 0
fi

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

# Find any configured build tree that has the generated headers.
generated_dir=""
for candidate in build/*/generated build/generated; do
    if [[ -f "$candidate/cpp_library_template/export.hpp" ]]; then
        generated_dir="$candidate"
        break
    fi
done

if [[ -z "$generated_dir" ]]; then
    echo "check_headers: no configured build tree found, skipping." >&2
    echo "check_headers: run 'cmake --preset dev' once to enable this check." >&2
    exit 0
fi

compiler="${CXX:-}"
if [[ -z "$compiler" ]]; then
    for candidate in g++ clang++ c++; do
        if command -v "$candidate" >/dev/null 2>&1; then
            compiler="$candidate"
            break
        fi
    done
fi

if [[ -z "$compiler" ]]; then
    echo "check_headers: no C++ compiler found, skipping." >&2
    exit 0
fi

status=0
for header in "$@"; do
    # Generated headers are checked through the ones that include them.
    case "$header" in
    *"/export.hpp" | *"/version.hpp") continue ;;
    esac

    if ! "$compiler" -std=c++20 -fsyntax-only -x c++ \
        -I include -I "$generated_dir" \
        -DCPP_LIBRARY_TEMPLATE_STATIC_DEFINE \
        "$header"; then
        echo "check_headers: $header does not compile standalone" >&2
        status=1
    fi
done

exit "$status"
